version: '3'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "3000:3000" 
    volumes:
      - .:/app
    networks: 
      - backend

networks:
  backend: 
